import { connectDatabase, disconnectDatabase } from "../config/database";
import { Robot } from "../models/Robot";

const sampleRobots = [
    // Robots 1-10
    {
        serialNumber: "AR001",
        type: "TUGGER",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 1",
        batteryCharge: 85,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "POSITION_ACKNOWLEDGED",
    },
    {
        serialNumber: "AR002",
        type: "CONVEYOR",
        manufacturer: "ABB Robotics",
        location: "Waypoint 3",
        batteryCharge: 45,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 2,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR003",
        type: "FORKLIFT",
        manufacturer: "KUKA",
        location: "Waypoint 2",
        batteryCharge: 92,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "IGNORED",
    },
    {
        serialNumber: "AR004",
        type: "TUGGER",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 5",
        batteryCharge: 12,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "POSITION_ACKNOWLEDGED",
    },
    {
        serialNumber: "AR005",
        type: "CONVEYOR",
        manufacturer: "Fanuc",
        location: "Waypoint 4",
        batteryCharge: 78,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR006",
        type: "FORKLIFT",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 6",
        batteryCharge: 23,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR007",
        type: "TUGGER",
        manufacturer: "ABB Robotics",
        location: "Waypoint 7",
        batteryCharge: 67,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR008",
        type: "CONVEYOR",
        manufacturer: "KUKA",
        location: "Waypoint 8",
        batteryCharge: 3,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR009",
        type: "FORKLIFT",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 9",
        batteryCharge: 56,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR010",
        type: "TUGGER",
        manufacturer: "Fanuc",
        location: "Waypoint 10",
        batteryCharge: 34,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },

    // Robots 11-20
    {
        serialNumber: "AR011",
        type: "CONVEYOR",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 11",
        batteryCharge: 88,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR012",
        type: "FORKLIFT",
        manufacturer: "ABB Robotics",
        location: "Waypoint 12",
        batteryCharge: 41,
        status: "inactive",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR013",
        type: "TUGGER",
        manufacturer: "KUKA",
        location: "Waypoint 13",
        batteryCharge: 95,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR014",
        type: "CONVEYOR",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 14",
        batteryCharge: 29,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR015",
        type: "FORKLIFT",
        manufacturer: "Fanuc",
        location: "Waypoint 15",
        batteryCharge: 61,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR016",
        type: "TUGGER",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 16",
        batteryCharge: 17,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR017",
        type: "CONVEYOR",
        manufacturer: "ABB Robotics",
        location: "Waypoint 17",
        batteryCharge: 80,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR018",
        type: "FORKLIFT",
        manufacturer: "KUKA",
        location: "Waypoint 18",
        batteryCharge: 54,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR019",
        type: "TUGGER",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 19",
        batteryCharge: 73,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR020",
        type: "CONVEYOR",
        manufacturer: "Fanuc",
        location: "Waypoint 20",
        batteryCharge: 8,
        status: "inactive",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },

    // Robots 21-30
    {
        serialNumber: "AR021",
        type: "FORKLIFT",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 21",
        batteryCharge: 66,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR022",
        type: "TUGGER",
        manufacturer: "ABB Robotics",
        location: "Waypoint 22",
        batteryCharge: 39,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR023",
        type: "CONVEYOR",
        manufacturer: "KUKA",
        location: "Waypoint 23",
        batteryCharge: 90,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR024",
        type: "FORKLIFT",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 24",
        batteryCharge: 21,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
        },
    {
        serialNumber: "AR025",
        type: "TUGGER",
        manufacturer: "Fanuc",
        location: "Waypoint 25",
        batteryCharge: 82,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR026",
        type: "CONVEYOR",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 26",
        batteryCharge: 47,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR027",
        type: "FORKLIFT",
        manufacturer: "ABB Robotics",
        location: "Waypoint 27",
        batteryCharge: 91,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR028",
        type: "TUGGER",
        manufacturer: "KUKA",
        location: "Waypoint 28",
        batteryCharge: 15,
        status: "inactive",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR029",
        type: "CONVEYOR",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 29",
        batteryCharge: 76,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR030",
        type: "FORKLIFT",
        manufacturer: "Fanuc",
        location: "Waypoint 30",
        batteryCharge: 33,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },

    // Robots 31-40
    {
        serialNumber: "AR031",
        type: "TUGGER",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 31",
        batteryCharge: 69,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR032",
        type: "CONVEYOR",
        manufacturer: "ABB Robotics",
        location: "Waypoint 32",
        batteryCharge: 52,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR033",
        type: "FORKLIFT",
        manufacturer: "KUKA",
        location: "Waypoint 33",
        batteryCharge: 84,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR034",
        type: "TUGGER",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 34",
        batteryCharge: 19,
        status: "inactive",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR035",
        type: "CONVEYOR",
        manufacturer: "Fanuc",
        location: "Waypoint 35",
        batteryCharge: 75,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR036",
        type: "FORKLIFT",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 36",
        batteryCharge: 42,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR037",
        type: "TUGGER",
        manufacturer: "ABB Robotics",
        location: "Waypoint 37",
        batteryCharge: 87,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR038",
        type: "CONVEYOR",
        manufacturer: "KUKA",
        location: "Waypoint 38",
        batteryCharge: 26,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR039",
        type: "FORKLIFT",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 39",
        batteryCharge: 63,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR040",
        type: "TUGGER",
        manufacturer: "Fanuc",
        location: "Waypoint 40",
        batteryCharge: 11,
        status: "inactive",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },

    // Robots 41-50
    {
        serialNumber: "AR041",
        type: "CONVEYOR",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 41",
        batteryCharge: 89,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR042",
        type: "FORKLIFT",
        manufacturer: "ABB Robotics",
        location: "Waypoint 42",
        batteryCharge: 37,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR043",
        type: "TUGGER",
        manufacturer: "KUKA",
        location: "Waypoint 43",
        batteryCharge: 71,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR044",
        type: "CONVEYOR",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 44",
        batteryCharge: 14,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR045",
        type: "FORKLIFT",
        manufacturer: "Fanuc",
        location: "Waypoint 45",
        batteryCharge: 93,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR046",
        type: "TUGGER",
        manufacturer: "Boston Dynamics",
        location: "Waypoint 46",
        batteryCharge: 48,
        status: "charging",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR047",
        type: "CONVEYOR",
        manufacturer: "ABB Robotics",
        location: "Waypoint 47",
        batteryCharge: 77,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR048",
        type: "FORKLIFT",
        manufacturer: "KUKA",
        location: "Waypoint 48",
        batteryCharge: 24,
        status: "inactive",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR049",
        type: "TUGGER",
        manufacturer: "Amazon Robotics",
        location: "Waypoint 49",
        batteryCharge: 86,
        status: "active",
        connectivity: true,
        emergencyStop: false,
        softwareStatus: 0,
        hardwareStatus: 0,
        batteryStatus: 1,
        networkStatus: 0,
        usageLevel: "ACKNOWLEDGED",
    },
    {
        serialNumber: "AR050",
        type: "CONVEYOR",
        manufacturer: "Fanuc",
        location: "Waypoint 50",
        batteryCharge: 55,
        status: "error",
        connectivity: false,
        emergencyStop: true,
        softwareStatus: 2,
        hardwareStatus: 1,
        batteryStatus: 2,
        networkStatus: 2,
        usageLevel: "ACKNOWLEDGED",
    },
];

const seedDatabase = async () => {
    try {
        await connectDatabase();

        // Clear existing robots
        await Robot.deleteMany({});
        console.log("Cleared existing robots");

        // Insert sample robots
        const robots = await Robot.insertMany(sampleRobots);
        console.log(`Inserted ${robots.length} robots`);

        // Show status distribution
        const statusCounts = await Robot.aggregate([
            {
                $group: {
                    _id: "$status",
                    count: { $sum: 1 },
                },
            },
        ]);
        console.log("Status distribution:", statusCounts);

        console.log("Database seeded successfully!");
    } catch (error) {
        console.error("Error seeding database:", error);
    } finally {
        await disconnectDatabase();
    }
};

// Run the seed function
seedDatabase();
